### ISSUE TITLE
Add TimeZone parameter (Optional)

### ISSUE THREAD

**Issue by luizcarlosfaria** [PlagueHO/Powershell#10]
Please, make Timezone as new optional parameter.

**Comment by PlagueHO** [comment]
All done. See latest Master build. Thanks! :)

**Comment by luizcarlosfaria** [comment]
Thank you,
but, you forgive a "," char before the new parameter.

**Comment by PlagueHO** [comment]
Apologies - that was pretty careless of me! Fixed now. Sorry about that.

**Comment by luizcarlosfaria** [comment]
Again thank you,
but the comma mus putted after parameter definition, 

Today version is:

```powershell
[ValidateNotNullOrEmpty()],
[String]$Edition = 'CORESYSTEMSERVER_INSTALL'
```

But to solve interpreter issues, we need that to be:

```powershell
[ValidateNotNullOrEmpty()]
[String]$Edition = 'CORESYSTEMSERVER_INSTALL',
```

**Comment by PlagueHO** [comment]
I'm so embarrassed! Making so many mistakes. Corrected now. I have access to my VM's now so I'll go and test it properly. Thanks for your help and patience.

**Comment by luizcarlosfaria** [comment]
Don't worry, it's a pleasure can help and is very gratifying does not fork a new project.
Best regards
