### ISSUE TITLE
Are you planning to publish DSCTools to the PSGallery?

### ISSUE THREAD

**Issue by PSSubmariner** [PlagueHO/Powershell#11]
I was looking through your code and you have a lot of great functions in your module. I checked the PSGallery and couldn't find it there. Am I just missing it or have you not published it?

**Comment by PlagueHO** [comment]
Hi @PSSubmariner - Doh! I thought I had, but looks like I'd forgotten. I might move this to it's own repo and then set up an automated pipeline to publish it. Shouldn't take long. Thanks for pointing this out.

**Comment by PlagueHO** [comment]
Hi @PSSubmariner - I have now published this to the gallery:
https://www.powershellgallery.com/packages/DSCTools

I have also moved the entire project to a new repo so that it can have it's on CI/CD pipeline for automated deployment:
https://github.com/PlagueHO/DSCTools

Thank you!
